
import './globals.css';
import { Inter, Manrope } from 'next/font/google';
import Header from "@/src/components/Header";
import { cx } from "@/src/utils";
import { Footer } from '../components/Footer';
import siteMetadata from '../utils/siteMetaData';



const inter = Inter({ subsets: ['latin'], display: "swap", variable: "--font-in" })
const manrope = Manrope({ subsets: ['latin'], display: "swap", variable: "--font-mr" })

export const metadata = {
  metadataBase: new URL(siteMetadata.siteUrl), 
    title: {
      template: `%s | ${siteMetadata.title}`,
      default: siteMetadata.title,

    },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.variable,
          manrope.variable,
          "font-mr bg-light"
        )}
      > 
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
